### ISSUE TITLE
Armar mail para entrevista

### ISSUE THREAD

**Issue by LaMaldicionDeMandos** [Proyecto-UTN-2012/Proyecto-UTN-2012#1]
Orientacion:
    Para nenes de 3 a 12 años o sea nenes bien chiquitos.
    Ver que onda la hiper o o hipo sensibilidad.
    le contamos lo que pensamos en hacer (aclarar lo del valor agregado)

Actividades (en tres etapas):
    comunicacion
    autoayuda
    juegos
    socializacion

**Comment by mavs82** [comment]
Somos un grupo de 5 alumnos de la materia Proyecto del último año de la carrera Ingeniería en Sistemas de la Información de la Universidad Tecnológica Nacional.
Decidimos orientar nuestro proyecto al armado de una aplicación que pueda ser utilizable en el tratamiento de niños autistas.
En una primera instancia pensamos enfocar la aplicación al tratamiento de niños entre los 3 y 12 años de edad y además incluir diferentes actividades agrupadas en  4 aspectos a desarrollar:
Comunicación
Autoayuda
Socialización
Juegos
Igualmente pensamos en integrar a esta aplicación una función de recolección de datos para el profesional a cargo del tratamiento del niño.
Si bien hemos estado investigando sobre el autismo y su tratamiento desearíamos tener el punto de vista de un profesional con respecto a:
-   Tareas a incluir con el fin de desarrollar los 4 puntos antes expuestos.
-   Información relevante para el profesional según cada tarea.
-   Aspectos a tener en cuenta según hiper e hipo sensibilidades presentes.
-   Factibilidad de uso dentro del rango etario elegido.
  Cualquier otra apreciación o corrección que pueda ser brindad será muy agradecida.
